basePath: /api
definitions:
  dto.CountryCreateOrUpdateRequest:
    properties:
      name:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - name
    type: object
  dto.GetOtpRequest:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - mobileNumber
    type: object
  dto.LoginByUsernameRequest:
    properties:
      password:
        minLength: 6
        type: string
      username:
        minLength: 5
        type: string
    required:
    - password
    - username
    type: object
  dto.RegisterLoginByMobileRequest:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
      otp:
        maxLength: 6
        minLength: 6
        type: string
    required:
    - mobileNumber
    - otp
    type: object
  dto.RegisterUserByUsernameRequest:
    properties:
      email:
        minLength: 6
        type: string
      firstName:
        minLength: 3
        type: string
      lastName:
        minLength: 6
        type: string
      password:
        minLength: 6
        type: string
      username:
        minLength: 5
        type: string
    required:
    - firstName
    - lastName
    - password
    - username
    type: object
  helpers.BaseHttpResponse:
    properties:
      error: {}
      result: {}
      result_code:
        type: integer
      success:
        type: boolean
      validation_errors:
        items:
          $ref: '#/definitions/validations.ValidationError'
        type: array
    type: object
  validations.ValidationError:
    properties:
      message:
        type: string
      property:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: golang web api
  title: Golang Web API
  version: "1.0"
paths:
  /v1/country/create:
    post:
      consumes:
      - application/json
      description: create a country in db
      parameters:
      - description: CountryCreateOrUpdateRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.CountryCreateOrUpdateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
      security:
      - BearerAuth: []
      tags:
      - Country
  /v1/country/find/{countryId}:
    get:
      consumes:
      - application/json
      description: Retrieves a country from the database using its ID
      parameters:
      - description: Country ID
        in: path
        name: countryId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
      security:
      - BearerAuth: []
      summary: Find a country by ID
      tags:
      - Country
  /v1/users/login-by-username:
    post:
      consumes:
      - application/json
      description: login user by username
      parameters:
      - description: LoginByUsernameRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginByUsernameRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
      tags:
      - Users
  /v1/users/register-by-username:
    post:
      consumes:
      - application/json
      description: register user by username
      parameters:
      - description: RegisterUserByUsernameRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterUserByUsernameRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
      tags:
      - Users
  /v1/users/register-login-by-mobile:
    post:
      consumes:
      - application/json
      description: register login user mobile number
      parameters:
      - description: RegisterLoginByMobileRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterLoginByMobileRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
      tags:
      - Users
  /v1/users/send-otp:
    post:
      consumes:
      - application/json
      description: send otp to user
      parameters:
      - description: GetOtpRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.GetOtpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
      tags:
      - Users
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
