definitions:
  dto.GetOtpRequest:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - mobileNumber
    type: object
  dto.LoginByUsernameRequest:
    properties:
      password:
        minLength: 6
        type: string
      username:
        minLength: 5
        type: string
    required:
    - password
    - username
    type: object
  dto.RegisterLoginByMobileRequest:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
      otp:
        maxLength: 6
        minLength: 6
        type: string
    required:
    - mobileNumber
    - otp
    type: object
  dto.RegisterUserByUsernameRequest:
    properties:
      email:
        minLength: 6
        type: string
      firstName:
        minLength: 3
        type: string
      lastName:
        minLength: 6
        type: string
      password:
        minLength: 6
        type: string
      username:
        minLength: 5
        type: string
    required:
    - firstName
    - lastName
    - password
    - username
    type: object
  helpers.BaseHttpResponse:
    properties:
      error: {}
      result: {}
      result_code:
        type: integer
      success:
        type: boolean
      validation_errors:
        items:
          $ref: '#/definitions/validations.ValidationError'
        type: array
    type: object
  validations.ValidationError:
    properties:
      message:
        type: string
      property:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/users/login-by-username:
    post:
      consumes:
      - application/json
      description: login user by username
      parameters:
      - description: LoginByUsernameRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginByUsernameRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
      tags:
      - Users
  /v1/users/register-by-username:
    post:
      consumes:
      - application/json
      description: register user by username
      parameters:
      - description: RegisterUserByUsernameRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterUserByUsernameRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
      tags:
      - Users
  /v1/users/register-login-by-mobile:
    post:
      consumes:
      - application/json
      description: register login user mobile number
      parameters:
      - description: RegisterLoginByMobileRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterLoginByMobileRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
      tags:
      - Users
  /v1/users/send-otp:
    post:
      consumes:
      - application/json
      description: send otp to user
      parameters:
      - description: GetOtpRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.GetOtpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/helpers.BaseHttpResponse'
      tags:
      - Users
swagger: "2.0"
