server:
  port: 5005
  runMode: debug
password:
  minLength: 4
  includeChars: true
  includeDigits: true
  includeLowercase: true
  includeUppercase: true
logger:
  filePath: ../logs/go.log
  encoding: json
  level: debug
  logger: zap
cors:
  allowOrigin: "*"
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: admin
  dbName: car_sale_db
  sslMode: disable
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5
redis:
  host: localhost
  port: 6379
  password: newpassword
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  minIdleConnections: 500
  poolSize: 10
  poolTimeout: 15
otp:
  duration: 120
  digits: 6
  limiter: 100   
jwt:
  secret: "mySecretKey"
  refreshSecret: "myRefreshSecret"
  accessTokenExpireDuration: 60
  refreshTokenExpireDuration: 360